import * as chrono from "chrono-node";

// BYO parser — turns the KEY: VALUE timeline that the user's own LLM produced
// (using byo-template.txt) into a structured project. Pure + deterministic; NO
// LLM is involved. Forgiving of LLM quirks (stray commentary, bullet/number
// prefixes, date-format variants, case), strict in its logic.

export type ByoEvent = {
  date: string; // YYYY-MM-DD
  title: string;
  type: "node" | "ambition";
  informations: string[];
  contexts: string[];
};
export type ByoProject = { title: string; tags: string[]; autoGenerated: boolean };
export type ByoParseResult = {
  project: ByoProject;
  events: ByoEvent[];
  skippedCount: number; // blocks with a DATE we couldn't parse
  truncatedCount: number; // subnode bodies trimmed to the char ceiling
};

const MAX_EVENTS = 50;
const INFO_MAX = 150;
const CONTEXT_MAX = 300;
const MAX_TAGS = 5;
const SINGLE_KEYS = new Set(["PROJECT", "TAGS", "DATE", "TITLE", "TYPE"]);

// --- preprocessing -----------------------------------------------------------
function preprocessLine(line: string): string {
  let s = line.replace(/\s+$/, ""); // trailing whitespace
  s = s.replace(/^\s+/, ""); // leading whitespace
  s = s.replace(/^[-*•]\s+/, ""); // leading bullet (needs a space → won't eat "---")
  s = s.replace(/^\d+[.)]\s+/, ""); // leading "1. " / "2) "
  return s;
}

// A horizontal rule: 3+ of the same dash/star/underscore (spaces ignored).
function isHr(line: string): boolean {
  const c = line.replace(/\s/g, "");
  return c.length >= 3 && (/^-+$/.test(c) || /^\*+$/.test(c) || /^_+$/.test(c));
}

// --- truncation (word boundary + ellipsis, length ≤ max) --------------------
function truncateAtWord(text: string, max: number): { body: string; truncated: boolean } {
  const t = text.trim();
  if (t.length <= max) return { body: t, truncated: false };
  const slice = t.slice(0, max - 1);
  const lastSpace = slice.lastIndexOf(" ");
  const cut = lastSpace > Math.floor(max * 0.6) ? slice.slice(0, lastSpace) : slice;
  return { body: cut.trimEnd() + "…", truncated: true };
}

// --- date parsing (chrono accepts ISO, "April 15 2026", "15/04/2026", …) ----
function parseDate(raw: string): string | null {
  const t = (raw ?? "").trim();
  if (!t) return null;
  const d = chrono.parseDate(t);
  if (!d || Number.isNaN(d.getTime())) return null;
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

export function parseByo(raw: string): ByoParseResult {
  // 1. preprocessing
  const lines = (raw ?? "").replace(/\r\n?/g, "\n").split("\n").map(preprocessLine);

  // 2. block splitting on one-or-more blank lines OR horizontal rules
  const blocks: string[][] = [];
  let cur: string[] = [];
  for (const l of lines) {
    if (l.trim() === "" || isHr(l)) {
      if (cur.length) {
        blocks.push(cur);
        cur = [];
      }
    } else {
      cur.push(l);
    }
  }
  if (cur.length) blocks.push(cur);

  // 3 + 4. per-block parse + classify
  let project: ByoProject | null = null;
  const events: ByoEvent[] = [];
  let skippedCount = 0;

  for (const block of blocks) {
    const single: Record<string, string> = {};
    const info: string[] = [];
    const context: string[] = [];
    for (const line of block) {
      const idx = line.indexOf(":");
      if (idx < 0) continue; // no colon → skip silently
      const key = line.slice(0, idx).trim().toUpperCase();
      const value = line.slice(idx + 1).trim();
      if (key === "INFO") {
        if (value) info.push(value);
      } else if (key === "CONTEXT") {
        if (value) context.push(value);
      } else if (SINGLE_KEYS.has(key)) {
        single[key] = value; // last wins
      }
      // unrecognized key → skip silently
    }

    if ("PROJECT" in single) {
      const tags = (single.TAGS ?? "")
        .split(",")
        .map((t) => t.trim())
        .filter(Boolean)
        .slice(0, MAX_TAGS);
      project = { title: single.PROJECT.trim(), tags, autoGenerated: false };
      continue;
    }
    if ("DATE" in single) {
      const date = parseDate(single.DATE);
      if (!date) {
        skippedCount++;
        continue;
      }
      const type = (single.TYPE ?? "").trim().toLowerCase() === "ambition" ? "ambition" : "node";
      const title = (single.TITLE ?? "").trim() || `Event on ${date}`;
      events.push({ date, title, type, informations: info, contexts: context });
      continue;
    }
    // neither PROJECT nor DATE → skip silently
  }

  // 5. post-processing
  events.sort((a, b) => a.date.localeCompare(b.date));
  const capped = events.slice(0, MAX_EVENTS);

  let truncatedCount = 0;
  const trim = (arr: string[], max: number) =>
    arr.map((s) => {
      const { body, truncated } = truncateAtWord(s, max);
      if (truncated) truncatedCount++;
      return body;
    });
  for (const e of capped) {
    e.informations = trim(e.informations, INFO_MAX);
    e.contexts = trim(e.contexts, CONTEXT_MAX);
  }

  if (!project) {
    const earliest = capped[0]?.date ?? new Date().toISOString().slice(0, 10);
    project = { title: `Imported timeline · ${earliest}`, tags: [], autoGenerated: true };
  } else if (!project.title) {
    // PROJECT block existed but was blank — keep it non-auto, give it a title.
    const earliest = capped[0]?.date ?? new Date().toISOString().slice(0, 10);
    project.title = `Imported timeline · ${earliest}`;
  }

  // 6. return
  return { project, events: capped, skippedCount, truncatedCount };
}
