import * as chrono from "chrono-node";

// BYO parser — turns the KEY: VALUE timeline that the user's own LLM produced
// (using byo-template.txt) into a structured project. Pure + deterministic; NO
// LLM is involved. Forgiving of LLM quirks (stray commentary, bullet/number
// prefixes, date-format variants, case), strict in its logic.

export type ByoEvent = {
  date: string; // YYYY-MM-DD
  title: string;
  type: "node" | "ambition";
  tags: string[]; // per-node tags (subset of project tags); drives the node colour
  informations: string[];
  contexts: string[];
};
export type ByoProject = { title: string; tags: string[]; autoGenerated: boolean };
export type ByoParseResult = {
  project: ByoProject;
  events: ByoEvent[];
  skippedCount: number; // blocks with a DATE we couldn't parse
  truncatedCount: number; // subnode bodies trimmed to the char ceiling
};

const MAX_EVENTS = 50;
const INFO_MAX = 150;
const CONTEXT_MAX = 300;
const MAX_TAGS = 5; // project header tags
const NODE_TAGS_MAX = 4; // per-event tags (mirrors the AI path cap)

// --- preprocessing -----------------------------------------------------------
function preprocessLine(line: string): string {
  let s = line.replace(/\s+$/, ""); // trailing whitespace
  s = s.replace(/^\s+/, ""); // leading whitespace
  s = s.replace(/^[-*•]\s+/, ""); // leading bullet (needs a space → won't eat "---")
  s = s.replace(/^\d+[.)]\s+/, ""); // leading "1. " / "2) "
  return s;
}

// Normalize a "KEY" token: strip markdown decoration (heading #, blockquote >,
// emphasis * _ ~, inline-code `) and upper-case it. So "**DATE**", "### DATE",
// and "date" all resolve to "DATE".
function normalizeKey(key: string): string {
  return key
    .replace(/^[#>\s]+/, "")
    .replace(/[*_`~]/g, "")
    .trim()
    .toUpperCase();
}

// --- truncation (word boundary + ellipsis, length ≤ max) --------------------
function truncateAtWord(text: string, max: number): { body: string; truncated: boolean } {
  const t = text.trim();
  if (t.length <= max) return { body: t, truncated: false };
  const slice = t.slice(0, max - 1);
  const lastSpace = slice.lastIndexOf(" ");
  const cut = lastSpace > Math.floor(max * 0.6) ? slice.slice(0, lastSpace) : slice;
  return { body: cut.trimEnd() + "…", truncated: true };
}

// --- date parsing (chrono accepts ISO, "April 15 2026", "15/04/2026", …) ----
function parseDate(raw: string): string | null {
  const t = (raw ?? "").trim();
  if (!t) return null;
  const d = chrono.parseDate(t);
  if (!d || Number.isNaN(d.getTime())) return null;
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

export function parseByo(raw: string): ByoParseResult {
  // 1. preprocessing
  const lines = (raw ?? "").replace(/\r\n?/g, "\n").split("\n").map(preprocessLine);

  // 2. line-driven scan. A new event begins at every DATE: line — we do NOT rely
  //    on blank lines to separate blocks (LLMs and clipboard pastes routinely
  //    drop them). PROJECT/TAGS set the project header; TITLE/TYPE/INFO/CONTEXT
  //    attach to the event currently being assembled.
  let project: ByoProject | null = null;
  let pendingTags: string[] = []; // TAGS seen before its PROJECT line
  const events: ByoEvent[] = [];
  let skippedCount = 0;

  let cur: ByoEvent | null = null; // event under construction (null between DATE lines)
  const flush = () => {
    if (cur) {
      if (!cur.title) cur.title = `Event on ${cur.date}`;
      events.push(cur);
      cur = null;
    }
  };

  for (const line of lines) {
    const idx = line.indexOf(":");
    if (idx < 0) continue; // no colon → not a KEY: VALUE line, skip silently
    const key = normalizeKey(line.slice(0, idx));
    // Strip a leading run of emphasis markers left over from a decorated key
    // (e.g. "**DATE:**" leaves the closing "**" on the value). Only when the run
    // is followed by whitespace/end, so genuine "*emphasis*" inside a value is kept.
    const value = line
      .slice(idx + 1)
      .replace(/^[*_~`]+(?=\s|$)/, "")
      .trim();

    switch (key) {
      case "PROJECT":
        flush();
        project = { title: value.trim(), tags: pendingTags, autoGenerated: false };
        pendingTags = [];
        break;
      case "TAGS": {
        const tags = value
          .split(",")
          .map((t) => t.trim())
          .filter(Boolean);
        // Inside an event block (a DATE has opened one) → per-node tags. Otherwise
        // it's the project header (or pending tags seen before PROJECT).
        if (cur) cur.tags = tags.slice(0, NODE_TAGS_MAX);
        else if (project) project.tags = tags.slice(0, MAX_TAGS);
        else pendingTags = tags.slice(0, MAX_TAGS);
        break;
      }
      case "DATE": {
        flush(); // finalize the previous event before starting a new one
        const date = parseDate(value);
        if (!date) {
          skippedCount++; // a DATE we couldn't parse — cur stays null, its fields are dropped
          break;
        }
        cur = { date, title: "", type: "node", tags: [], informations: [], contexts: [] };
        break;
      }
      case "TITLE":
        if (cur) cur.title = value.trim();
        break;
      case "TYPE":
        if (cur) cur.type = value.trim().toLowerCase() === "ambition" ? "ambition" : "node";
        break;
      case "INFO":
        if (cur && value) cur.informations.push(value);
        break;
      case "CONTEXT":
        if (cur && value) cur.contexts.push(value);
        break;
      // unrecognized key → skip silently
    }
  }
  flush(); // finalize the trailing event

  // 5. post-processing
  events.sort((a, b) => a.date.localeCompare(b.date));
  const capped = events.slice(0, MAX_EVENTS);

  let truncatedCount = 0;
  const trim = (arr: string[], max: number) =>
    arr.map((s) => {
      const { body, truncated } = truncateAtWord(s, max);
      if (truncated) truncatedCount++;
      return body;
    });
  for (const e of capped) {
    e.informations = trim(e.informations, INFO_MAX);
    e.contexts = trim(e.contexts, CONTEXT_MAX);
  }

  if (!project) {
    const earliest = capped[0]?.date ?? new Date().toISOString().slice(0, 10);
    project = { title: `Imported timeline · ${earliest}`, tags: [], autoGenerated: true };
  } else if (!project.title) {
    // PROJECT block existed but was blank — keep it non-auto, give it a title.
    const earliest = capped[0]?.date ?? new Date().toISOString().slice(0, 10);
    project.title = `Imported timeline · ${earliest}`;
  }

  // 6. return
  return { project, events: capped, skippedCount, truncatedCount };
}
