import { describe, it, expect } from "vitest";
import { parseByo } from "./parser";

const WELL_FORMED = `PROJECT: Vendor Contract Renewal
TAGS: contracts, supplier, Q2

DATE: 2026-04-12
TITLE: Negotiation opens
INFO: The vendor submitted a renewal proposal.
CONTEXT: Tier-1 supplier providing 60% of raw material.

DATE: 2026-05-01
TITLE: Final signature scheduled
INFO: Signing meeting set for May 1.
TYPE: ambition`;

describe("parseByo", () => {
  it("happy path: parses project, tags, events, subnodes, type", () => {
    const r = parseByo(WELL_FORMED);
    expect(r.project.title).toBe("Vendor Contract Renewal");
    expect(r.project.tags).toEqual(["contracts", "supplier", "Q2"]);
    expect(r.project.autoGenerated).toBe(false);
    expect(r.events).toHaveLength(2);
    expect(r.events[0]).toMatchObject({
      date: "2026-04-12",
      title: "Negotiation opens",
      type: "node",
      informations: ["The vendor submitted a renewal proposal."],
      contexts: ["Tier-1 supplier providing 60% of raw material."],
    });
    expect(r.events[1].type).toBe("ambition");
    expect(r.skippedCount).toBe(0);
    expect(r.truncatedCount).toBe(0);
  });

  it("order independence: PROJECT block at the end", () => {
    const input = `DATE: 2026-04-12
TITLE: Negotiation opens
INFO: A fact.

PROJECT: Late Project
TAGS: a, b`;
    const r = parseByo(input);
    expect(r.project.title).toBe("Late Project");
    expect(r.project.autoGenerated).toBe(false);
    expect(r.events).toHaveLength(1);
  });

  it("invalid dates are skipped and counted", () => {
    const input = `DATE: sometime last spring
TITLE: Fuzzy event
INFO: No real date here.

DATE: 2026-04-12
TITLE: Real event
INFO: Has a date.`;
    const r = parseByo(input);
    expect(r.events).toHaveLength(1);
    expect(r.events[0].title).toBe("Real event");
    expect(r.skippedCount).toBe(1);
  });

  it("empty input returns an empty, non-crashing result", () => {
    const r = parseByo("");
    expect(r.events).toHaveLength(0);
    expect(r.project.autoGenerated).toBe(true);
    expect(r.skippedCount).toBe(0);
    expect(r.truncatedCount).toBe(0);
  });

  it("ignores surrounding LLM commentary", () => {
    const input = `Sure! Here is your timeline based on the content you provided:

PROJECT: Real Project
TAGS: x

DATE: 2026-04-12
TITLE: Something happens
INFO: A fact.

I hope this helps! Let me know if you'd like any changes.`;
    const r = parseByo(input);
    expect(r.project.title).toBe("Real Project");
    expect(r.events).toHaveLength(1);
  });

  it("strips bullet and numbered prefixes", () => {
    const input = `PROJECT: Bulleted Project

- DATE: 2026-04-12
- TITLE: Bulleted event
1. INFO: First fact.
2. INFO: Second fact.`;
    const r = parseByo(input);
    expect(r.events).toHaveLength(1);
    expect(r.events[0].title).toBe("Bulleted event");
    expect(r.events[0].informations).toEqual(["First fact.", "Second fact."]);
  });

  it("sentinels are case-insensitive", () => {
    const input = `project: Lowercase Project

date: 2026-04-12
Title: Mixed case
Info: a fact
context: some background`;
    const r = parseByo(input);
    expect(r.project.title).toBe("Lowercase Project");
    expect(r.events[0]).toMatchObject({
      title: "Mixed case",
      informations: ["a fact"],
      contexts: ["some background"],
    });
  });

  it("collects multiple INFO and CONTEXT lines per event", () => {
    const input = `DATE: 2026-04-15
TITLE: Busy event
INFO: Fact one.
INFO: Fact two.
CONTEXT: Background one.
CONTEXT: Background two.`;
    const r = parseByo(input);
    expect(r.events[0].informations).toEqual(["Fact one.", "Fact two."]);
    expect(r.events[0].contexts).toEqual(["Background one.", "Background two."]);
  });

  it("per-node TAGS attach to the event without clobbering project tags", () => {
    const input = `PROJECT: Vendor Contract Renewal
TAGS: contracts, supplier, Q2

DATE: 2026-04-12
TITLE: Negotiation opens
TAGS: supplier
INFO: A fact.

DATE: 2026-04-15
TITLE: Pricing agreed
TAGS: contracts, supplier`;
    const r = parseByo(input);
    expect(r.project.tags).toEqual(["contracts", "supplier", "Q2"]); // header untouched
    expect(r.events[0].tags).toEqual(["supplier"]);
    expect(r.events[1].tags).toEqual(["contracts", "supplier"]);
  });

  it("caps per-node TAGS at 4", () => {
    const input = `DATE: 2026-04-12
TITLE: Many tags
TAGS: a, b, c, d, e, f`;
    const r = parseByo(input);
    expect(r.events[0].tags).toEqual(["a", "b", "c", "d"]);
  });

  it("accepts multiple date formats (ISO, natural, DD/MM/YYYY)", () => {
    const input = `DATE: 2026-04-12
TITLE: ISO

DATE: April 15 2026
TITLE: Natural

DATE: 20/04/2026
TITLE: Day-first`;
    const r = parseByo(input);
    const byTitle = Object.fromEntries(r.events.map((e) => [e.title, e.date]));
    expect(byTitle["ISO"]).toBe("2026-04-12");
    expect(byTitle["Natural"]).toBe("2026-04-15");
    expect(byTitle["Day-first"]).toBe("2026-04-20");
    expect(r.skippedCount).toBe(0);
  });

  it("truncates long INFO (150) and CONTEXT (300) at a word boundary", () => {
    const longInfo = "word ".repeat(60).trim(); // ~300 chars
    const longCtx = "word ".repeat(120).trim(); // ~600 chars
    const input = `DATE: 2026-04-12
TITLE: Long event
INFO: ${longInfo}
CONTEXT: ${longCtx}`;
    const r = parseByo(input);
    const e = r.events[0];
    expect(e.informations[0].length).toBeLessThanOrEqual(150);
    expect(e.informations[0].endsWith("…")).toBe(true);
    expect(e.contexts[0].length).toBeLessThanOrEqual(300);
    expect(e.contexts[0].endsWith("…")).toBe(true);
    expect(r.truncatedCount).toBe(2);
  });

  it("auto-generates a project when no PROJECT block is present", () => {
    const input = `DATE: 2026-04-12
TITLE: Lonely event
INFO: A fact.`;
    const r = parseByo(input);
    expect(r.project.autoGenerated).toBe(true);
    expect(r.project.title).toBe("Imported timeline · 2026-04-12");
  });

  it("parses events with NO blank lines between blocks (run-together output)", () => {
    // Real-world failure: an LLM (or a clipboard paste) drops the blank-line
    // separators, so PROJECT and every event run together with no gaps.
    const input = `PROJECT: Vasileiou Horizon Villas Booking
TAGS: horizon-villas, booking, lodgify
DATE: 2026-04-06
TITLE: Villa options offered
INFO: Diana and Celine villas presented as available similar options.
CONTEXT: Guest inquired about availability; Diana recommended as slightly larger.
DATE: 2026-04-12
TITLE: Guest selects larger villa
INFO: Nadia confirmed booking the larger villa (Roxana).
DATE: 2026-08-26
TITLE: Vasileiou stay begins
TYPE: ambition
INFO: Guest stay scheduled 26-30/8 at villa closest to the pool.`;
    const r = parseByo(input);
    expect(r.project.title).toBe("Vasileiou Horizon Villas Booking");
    expect(r.project.tags).toEqual(["horizon-villas", "booking", "lodgify"]);
    expect(r.project.autoGenerated).toBe(false);
    expect(r.events).toHaveLength(3);
    expect(r.events[0]).toMatchObject({ date: "2026-04-06", title: "Villa options offered", type: "node" });
    expect(r.events[1].title).toBe("Guest selects larger villa");
    expect(r.events[2]).toMatchObject({ date: "2026-08-26", type: "ambition" });
    expect(r.events[2].informations).toEqual(["Guest stay scheduled 26-30/8 at villa closest to the pool."]);
    expect(r.skippedCount).toBe(0);
  });

  it("tolerates markdown-decorated keys (**DATE:**, ### TITLE:, > INFO:)", () => {
    const input = `**PROJECT:** Decorated Project
**TAGS:** a, b

**DATE:** 2026-04-12
### TITLE: Markdown event
> INFO: A fact that survived the markdown.`;
    const r = parseByo(input);
    expect(r.project.title).toBe("Decorated Project");
    expect(r.project.tags).toEqual(["a", "b"]);
    expect(r.events).toHaveLength(1);
    expect(r.events[0]).toMatchObject({
      date: "2026-04-12",
      title: "Markdown event",
      informations: ["A fact that survived the markdown."],
    });
  });

  it("caps events at 50 after chronological sort", () => {
    const blocks = Array.from({ length: 60 }, (_, i) => {
      const day = String((i % 28) + 1).padStart(2, "0");
      return `DATE: 2026-04-${day}\nTITLE: Event ${i}`;
    });
    const r = parseByo(blocks.join("\n\n"));
    expect(r.events).toHaveLength(50);
  });
});
